### ISSUE TITLE
gale's kernel replacements break 38 upstream-passing Zephyr kernel suites at build time (10 causes; 18 from CONFIG_TIMESLICE_SIZE)

### ISSUE THREAD

**Issue by avrabe** [pulseengine/gale#401]
**[fathom (gale) — first real measurement from #396: gale's kernel replacements break 38 upstream-passing kernel suites, all at BUILD time]**

Source: the upstream-vs-gale delta job on #396 (run 35158736050, artifact `twister-results-gale`). Same twister invocation both legs (`--platform qemu_cortex_m3 --tag kernel --enable-slow`), gale leg with the 28 `CONFIG_GALE_KERNEL_*` from `zephyr/gale_overlay.conf`. **Gale was verifiably compiled in: 196 of 205 built configs carry `CONFIG_GALE_KERNEL_SEM=y`.** An earlier run of this leg silently built upstream (twister overrode OVERLAY_CONFIG), and that is fixed in #396.

| | upstream | gale |
|---|---|---|
| passed | 146 | 108 |
| failed | 1 | 1 (`kernel.timer.starve`, fails in both) |
| error | 0 | **40** |

**38 regressions (pass upstream, error with gale), 0 fixes.** Every one is a **build failure**. None is a behavioural test failure, so this says nothing yet about the runtime correctness of the replacements. It says the C shims only compile in the configurations gale's own CI builds. Grouped by twister's recorded reason:

| # | cause | suites |
|---|---|---|
| 18 | `error: 'CONFIG_TIMESLICE_SIZE' undeclared here (not in a function); did you mean 'CONFIG_DCACHE_LINE_SIZE'?` | `benchmark.kernel.latency`, `benchmark.sched_queues.multiq`, `benchmark.sched_queues.scalable`, `benchmark.sched_queues.simple`, `benchmark.thread_metric.basic`, `benchmark.thread_metric.cooperative` … |
| 6 | `undefined reference to `arch_system_halt'` | `kernel.no-mt.arbitrary_reason`, `kernel.no-mt.arbitrary_reason_negative`, `kernel.no-mt.cpu_exception`, `kernel.no-mt.oops`, `kernel.no-mt.panic`, `kernel.no-mt.zephyr_assert` |
| 4 | `error: 'obj_type_msgq' undeclared (first use in this function)` | `benchmark.kernel.latency.objcore`, `kernel.obj_core`, `kernel.obj_core.stats`, `kernel.obj_core.stats.api` |
| 2 | `error: macro "sys_port_trace_k_msgq_put_exit" requires 3 arguments, but only 2 given` | `kernel.objects.tracking`, `kernel.objects.tracking.minimallibc` |
| 2 | `undefined reference to `gale_k_event_wait_decide'` | `kernel.device`, `kernel.device.minimallibc` |
| 2 | `ld.bfd: warning: orphan section `.note.GNU-stack' from `/__w/gale/gale/gale/zephyr/../ffi/target/thumbv7m-none-eabi/release/libgale_ffi.a(co` | `kernel.device.linker_generator`, `linker.linker_generator` |
| 1 | `undefined reference to `k_malloc'` | `benchmark.kernel.core` |
| 1 | `error: passing argument 1 of 'sys_dlist_peek_head' from incompatible pointer type [-Wincompatible-pointer-types]` | `kernel.mutex.scalable` |
| 1 | `undefined reference to `z_pend_curr'` | `kernel.memory_slabs.api.no-mt` |
| 1 | `error: implicit declaration of function 'k_thread_system_pool_assign'; did you mean 'k_thread_heap_assign'? [-Wimplicit-function-declaration` | `kernel.threads.thread_stack` |

### What the grouping suggests (hypotheses, each to be confirmed from the build log)
- **`CONFIG_TIMESLICE_SIZE` undeclared (18):** a gale shim references a timeslicing symbol unconditionally. It breaks every `*_no_timeslicing` / `CONFIG_TIMESLICING=n` config, which is most of the thread_metric and sched/wait-queue benchmarks.
- **`arch_system_halt` undefined (6):** the `kernel.no-mt.*` family (`CONFIG_MULTITHREADING=n`). The fatal-path replacement assumes a symbol that config does not provide.
- **`obj_type_msgq` / `sys_port_trace_k_msgq_put_exit` arity (6):** object-core and tracing hooks (`CONFIG_OBJ_CORE`, tracing) drifted from upstream's signatures. This is likely the vendored-shim-vs-v4.4.x drift already noted in #391.
- **Undefined `gale_k_event_wait_decide`, `k_malloc`, `z_pend_curr`, `k_thread_system_pool_assign`:** the FFI or C side assumes a feature-set combination the config does not select.
- **Orphan `.note.GNU-stack` (2):** `linker_generator` configs treat that warning as fatal. The section comes from a gale object.

### Why this matters
gale's claim is a drop-in replacement of Zephyr kernel primitives. Drop-in has to hold across upstream's config space, not only across the default config gale's CI builds. This delta is the first oracle that can see that, and it is now wired into CI. It measures, it does not gate; the numbers above are its baseline.

### Proposed next steps
1. Fix the TIMESLICE cause first: 18 of 38 regressions from one symbol.
2. Make `--fail-on-regression` the gate once the count reaches a ledger that fails when an entry is fixed (same shape as `KNOWN_FAILING`).
3. Extend beyond build errors: once suites build, the runtime deltas are the replacement-correctness evidence.

**Comment by avrabe** [comment]
**[fathom (gale) — three causes fixed on `fix/gale-timeslice-depends-timeslicing` (30 of 38 by count), not yet measured]**

| cause | suites | fix | commit |
|---|---|---|---|
| `CONFIG_TIMESLICE_SIZE` undeclared | 18 | `GALE_KERNEL_TIMESLICE` now `depends on MULTITHREADING && TIMESLICING`, as upstream builds `timeslicing.c` only under `CONFIG_TIMESLICING` | 9c173b9 |
| undefined `arch_system_halt` | 6 | `gale_fatal.c` replaces `fatal.c` but had dropped its weak default; `tests/kernel/fatal/no-multithreading` calls it directly. Restored verbatim. `k_fatal_halt` also realigned: it called `arch_system_halt` only on x86 and otherwise spun with IRQs enabled. | bb4602f |
| `obj_type_msgq` undeclared + `k_msgq_put_exit` arity | 4 + 2 | object-core declaration and registration copied from upstream; every tracing call site matched to v4.4 (`put`/`put_front`/`get` exits take `timeout`; peek/purge are single-point hooks) | 10f2e77 |

**Not verified yet.** There is no local Zephyr workspace; the check is the upstream-vs-gale delta running on this branch, which needs #396 on main first. The PR waits for a CI slot.

Remaining 8, not started: `gale_k_event_wait_decide` undefined (2), orphan `.note.GNU-stack` under `linker_generator` (2), `k_malloc` undefined (1), `sys_dlist_peek_head` pointer type (1), `z_pend_curr` undefined (1), `k_thread_system_pool_assign` implicit (1).

**Comment by avrabe** [comment]
**[fathom (gale) — measured on #402: 38 → 14, not the ~8 I projected; and one new regression, now fixed]**

#402's upstream-vs-gale run (35195549957): gale **132 passed / 16 errored**, **14 regressions** (was 38), 0 fixes. Build success: 196/205 configs carry gale.

My earlier "30 of 38" counted one cause per suite. A build stops at its **first** error, so fixing a cause can expose the next one in the same suite. That is what happened: `kernel.objects.tracking*` now fails on **`sys_port_trace_k_condvar_wait_enter` (3 args vs 2)**, the condvar sibling of the msgq tracing drift. Counts per cause are lower bounds, not a plan.

**One regression was introduced by #402 itself.** `kernel.scheduler.simple_timeslicing` passed before and failed after with `undefined reference to gale_k_timeslice_tick_decide`. The cause is pre-existing and bigger than timeslicing: all 43 cargo invocations in `zephyr/CMakeLists.txt` built `libgale_ffi.a` into the source tree's shared `ffi/target`, while its feature set is per-build Kconfig. Parallel twister builds overwrote each other's library, and a library built for other features counted as up to date. Once the `*_no_timeslicing` configs built (thanks to the TIMESLICING fix), their timeslice-less library replaced the one `simple_timeslicing` linked. Fixed on #402 (3d5d4a7): a per-build `--target-dir` plus a feature stamp. The rerun will show whether `kernel.device*`'s `gale_k_event_wait_decide` undefined reference was the same race.

Remaining after #402 (from its run): `k_malloc` undefined (3), `sys_dlist_peek_head` pointer type (2), condvar tracing arity (2), `gale_k_event_wait_decide` undefined (2, possibly the race), `.note.GNU-stack` orphan (2), `z_pend_curr` undefined (1), `k_thread_system_pool_assign` implicit (1).

**Comment by avrabe** [comment]
**[fathom (gale) — #402 merged: 38 → 11; the race fix also cleared kernel.device*]**

Final run on #402 (35211716056): gale **135 passed / 13 errored, 11 regressions**. `kernel.scheduler.simple_timeslicing` is back to passing, and so are `kernel.device` + `kernel.device.minimallibc`: their `undefined gale_k_event_wait_decide` was the same shared-`ffi/target` race, not a separate cause.

**`k_malloc` undefined (5) is in the Zephyr fork, not gale:** the Gale patch to `kernel/CMakeLists.txt` skipped the whole `CONFIG_KERNEL_MEM_POOL` block, including the only definition of `K_HEAP_MEM_POOL_SIZE`. Fix proposed as pulseengine/zephyr#1 against `gale/sem-replacement`, **not merged, and a maintainer call**: gale CI clones that branch **by name, not a pinned revision**, so merging it changes every gale CI run at once. That floating dependency is a reproducibility gap in its own right.

Remaining after that: `sys_dlist_peek_head` pointer type (2), condvar tracing arity (2), `.note.GNU-stack` orphan under linker_generator (2), `z_pend_curr` undefined in no-mt (1), `k_thread_system_pool_assign` implicit (1).

**Comment by avrabe** [comment]
**[fathom (gale) — CLOSED by measurement: 38 → 0 regressions]**

Final delta on #404's merge commit (run 35266155898), with pulseengine/zephyr#1 merged into `gale/sem-replacement`:

| | upstream | gale |
|---|---|---|
| executed | 147 | 147 |
| passed | 146 | 146 |
| errored | 0 | **0** |

**Regressions gale introduces: 0.** The one failure, `kernel.timer.starve`, fails on BOTH sides and is ledgered as upstream's (#394).

How it went, each step measured rather than projected:

| step | regressions | what it was |
|---|---|---|
| first honest run (#396) | 38 | gale's config finally reached the builds; the earlier "gale" leg was a second upstream run |
| #402 | 14 | TIMESLICING dependency, weak `arch_system_halt`, msgq obj-core + tracing |
| #402 (race fix) | 11 | all 43 cargo builds shared one `ffi/target` for a per-build-Kconfig library |
| #404 | 4 | condvar tracing arity + `CONFIG_WAITQ_SCALABLE`, mem_slab no-MT, `.note.GNU-stack` orphan |
| + zephyr#1 | **0** | `K_HEAP_MEM_POOL_SIZE` defined again when Gale replaces `mempool.c` |

`kernel.threads.thread_stack`'s implicit `k_thread_system_pool_assign` WAS the same fork cause — recorded here because I had only called it likely.

Two things this leaves behind, deliberately not silent:
1. **gale CI clones `gale/sem-replacement` by branch name, not by revision.** This result is therefore not reproducible from gale's history alone. Worth a pinned revision.
2. **Condvar broadcast caps its waiter count at 256 and wakes only that many, where upstream wakes all** (`zephyr/gale_condvar.c`). Untouched here; a deviation for the verified-decision owners to review.

Closing: the property this issue asked for — gale's replacements build across upstream's config space — now holds and is gated by a job that measures it on every PR.
